stages:  # Définition des étapes
  - build
  - test
  - deploy

variables:
  GLOBAL_VAR: "Hello, GitLab!"
  MAVEN_CLI_OPTS: "-s settings.xml --batch-mode --errors --fail-at-end --show-version"
  DOCKER_IMAGE: "maven:3.8.6-openjdk-17"

before_script:
  - echo "Initialisation du pipeline CI/CD"

# 🏗️ Build Job
build-job:
  stage: build
  image: $DOCKER_IMAGE
  script:
    - echo "Compilation du projet"
    - mvn $MAVEN_CLI_OPTS clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1h

# ✅ Test Job
test-job:
  stage: test
  image: $DOCKER_IMAGE
  script:
    - echo "Exécution des tests unitaires"
    - mvn $MAVEN_CLI_OPTS test
  only:
    - main
    - develop

# 🚀 Déploiement en staging (branche main uniquement)
deploy-staging:
  stage: deploy
  only:
    - main
  script:
    - echo "Déploiement de l'application en staging"
    - scp target/*.jar user@staging-server:/opt/app/
    - ssh user@staging-server 'systemctl restart springboot-app'
  when: manual  # Déploiement manuel pour éviter un déploiement automatique

# 🔥 Déploiement en production avec validation manuelle
deploy-production:
  stage: deploy
  only:
    - main
  script:
    - echo "Déploiement en production"
    - scp target/*.jar user@prod-server:/opt/app/
    - ssh user@prod-server 'systemctl restart springboot-app'
  when: manual  # Validation manuelle requise

# 📦 Gestion du cache
cache-job:
  stage: build
  script:
    - mkdir -p .cache
    - echo "Cache stocké"
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .cache/
